[package]
name = "bcs-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
bcs-core = { path = "../core" }

[[bin]]
name = "decode_bytes"
path = "fuzz_targets/decode_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "get_path"
path = "fuzz_targets/get_path.rs"
test = false
doc = false
bench = false
